import type { Metadata } from 'next'
import Link from 'next/link'
import localFont from 'next/font/local'
import { Button } from '@tapes-monorepo/ui'
import './globals.css'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative h-screen w-screen overflow-hidden pt-[32px] text-zinc-800 antialiased dark:text-zinc-100`}
      >
        <div id="titlebar" className="absolute top-0 z-50 h-[32px] w-full" />
        <nav className="w-full">
          <ul className="flex w-full justify-between gap-1 p-1">
            {navigationConfig.map(({ label, href }) => (
              <li key={href} className="size-full">
                <Link href={href}>
                  <Button className="p-4">{label}</Button>
                </Link>
              </li>
            ))}
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}

const navigationConfig = [
  { label: 'Recorder', href: '/recorder' },
  { label: 'Library', href: '/library' },
  { label: 'Settings', href: '/settings' },
  // { label: 'About', href: '/about' },
] as const
